modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/jadeposting/gatekeep/issues"
license = "LGPL-3.0"

[[mods]]
modId = "gatekeep"
version = "${version}"
displayName = "gatekeep"
authors = "jadeposting"
description = '''
Gatekeep removes all chat-signing related indicators from chat & toasts
'''
logoFile = "icon.png"

[[dependencies.gatekeep]]
modId = "neoforge"
type = "required"
versionRange = "[21.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.gatekeep]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.4,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "gatekeep.mixins.json"
